---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Introduction

<!-- #region -->
The Project Performance Database (PPD) Version 2.0 offers a unique insight into the world of foreign aid. It encompasses evaluations from 12 bilateral and multilateral aid agencies. The data includes over 20,000 unique foreign aid projects over the span of 1956 to 2016 across 183 recipient countries. The data comes from AidData, a reputable international development research lab. It is currently the world’s largest database on development projects.

The dataset is accompanied by a Codebook PDF which provides insight into the variables within the dataset, including breaking down the meaning of each column name, explaining acronyms and suggesting The data set has several variable types, including variables that draw from multiple donors in the dataset (Combined Variables), variables drawn from AidData’s dataset (AidData Variables) and variables that are donor-specific (Donor-Specific Variables). The Codebook concludes with Suggested variables which might be constructed from the donor-specific variables. 


The dataset includes the following donor organisations:

AfricanDB: African Development Bank

AsianDB: Asian Development Bank

CDB: Caribbean Development Bank

DFAT: Australia’s Department of Foreign Affairs and Trade 

DFID: UK’s Department for International Development

GEF: Global Environment Fund

GFATM: Global Fund for AIDS, Tuberculosis, and Malaria

GiZ: German Society for International Cooperation

IFAD: International Fund for Agricultural Development

JICA: Japanese International Cooperation Agency 

KfW: German Development Bank

WB: World Bank

The objective of this report is to delve into the multifaceted dynamics of international aid as depicted in the PPD 2.0 dataset. Our analysis aims to, first, scrutinise the project outcomes and operational efficiencies of prominent donors like the World Bank (WB), African Development Bank (AfricanDB), German Society for International Cooperation (GiZ), and German Development Bank(KfW); and second, identify overarching trends across all included organisations. Given the expansive nature of the dataset, with its 494 columns and over 21,000 projects, our investigation strategically focuses on the most data-rich and consistently populated initial 30 columns. This approach is designed to maximize the depth and reliability of our insights within the constraints of time and resources.

This report is organised to provide a clear, sequential exploration of PPD 2.0. It commences with an introduction that contextualises the dataset within the broader landscape of foreign aid, through a literature review, which connects our study to existing academic knowledge in the field. Our analysis section presents our core findings, followed by a discussion that interprets these results in the broader context of international development. The report concludes with a summation of our key insights and recommendations for future research in this field.

<!-- #endregion -->
